name: Release
on:
  push:
    tags:
      - 'v*.*.*'

# Add permissions block
permissions:
  contents: write
  discussions: write
  packages: write

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Clear updater cache
        run: rm -rf ~/.cache/enzyme-updater || true

      - name: Install dependencies
        run: pnpm install

      - name: Install the Apple certificate
        if: matrix.os == 'macos-latest'
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # Create keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          
          # Import certificate
          echo $BUILD_CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
          
          # Clean up
          rm certificate.p12

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libopenjp2-tools \
            rpm \
            fakeroot \
            dpkg \
            ruby-dev \
            gcc \
            make

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Mac-specific variables
          CSC_LINK: ${{ matrix.os == 'macos-latest' && secrets.BUILD_CERTIFICATE_BASE64 || '' }}
          CSC_KEY_PASSWORD: ${{ matrix.os == 'macos-latest' && secrets.P12_PASSWORD || '' }}
          APPLE_ID: ${{ matrix.os == 'macos-latest' && secrets.APPLE_ID || '' }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ matrix.os == 'macos-latest' && secrets.APPLE_APP_SPECIFIC_PASSWORD || '' }}
          APPLE_TEAM_ID: ${{ matrix.os == 'macos-latest' && secrets.APPLE_TEAM_ID || '' }}
          NOTARIZE_APPLE_ID: ${{ matrix.os == 'macos-latest' && secrets.APPLE_ID || '' }}
          NOTARIZE_APPLE_PASSWORD: ${{ matrix.os == 'macos-latest' && secrets.APPLE_APP_SPECIFIC_PASSWORD || '' }}
          NOTARIZE_TEAM_ID: ${{ matrix.os == 'macos-latest' && secrets.APPLE_TEAM_ID || '' }}
        run: |
          pnpm run build
          pnpm run build:${{ matrix.os == 'macos-latest' && 'mac' || matrix.os == 'windows-latest' && 'win' || 'linux' }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ github.ref_name }}
          files: |
            ${{ matrix.os == 'macos-latest' && 'dist/*.dmg' || '' }}
            ${{ matrix.os == 'macos-latest' && 'dist/latest-mac.yml' || '' }}
            ${{ matrix.os == 'macos-latest' && 'dist/*.zip' || '' }}
            ${{ matrix.os == 'macos-latest' && 'dist/*.blockmap' || '' }}
            ${{ matrix.os == 'windows-latest' && 'dist/*.exe' || '' }}
            ${{ matrix.os == 'windows-latest' && 'dist/latest.yml' || '' }}
            ${{ matrix.os == 'ubuntu-latest' && 'dist/*.AppImage' || '' }}
            ${{ matrix.os == 'ubuntu-latest' && 'dist/*.snap' || '' }}
            ${{ matrix.os == 'ubuntu-latest' && 'dist/latest-linux.yml' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 